name: Create Alpha Release
on:
  push:
    branches:
      - main
  
jobs:
  build:
    name: Create Alpha Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Package Version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install
      run: npm ci --no-optional
    - name: Package
      run: npm run vsce:package
    - name: Tag commit
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: ${{ steps.package-version.outputs.current-version }}-alpha
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.package-version.outputs.current-version }}-alpha
        release_name: Alpha Release ${{ steps.package-version.outputs.current-version }}-alpha
        draft: true
        prerelease: true
    - name: Upload Alpha Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_name: tabnine-vscode.vsix
        asset_path: ./tabnine-vscode-${{ steps.package-version.outputs.current-version }}-alpha.vsix
        asset_content_type: application/octet-stream